<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Advance_Python/NumPy/Numpy_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Q1.what is difference between list and an Array?

# Array : An array is a n-dimensional collection of same data type.
#          It has contiguous memory allocation.
#          It use less memory compare to list.
#          It allows to perform vactorize operation instead of loops.

a=np.array([1,2,3])
a


# List : List is collection of mix data types.
#         it use more memory compare to numpy array.
#         It uses loop to perform operation on each element.

b=[1,2,3]
b


[1, 2, 3]

In [ ]:
# Q2. Create an array and calcualte shape , size and dimension of an array.

a=np.array([[1,2,3],[4,5,6]])
a

print("Shape: ",a.shape)
print("Size: ",a.size)
print("Dimension: ",a.ndim)

Shape:  (2, 3)
Size:  6
Dimension:  2


In [ ]:
# Q3. What is Zeros, ones , eye, diagonal , linspace , unique function , explain with the code of example?


# Zeros==> Zeros is a numpy in-built function which is used to create a array with all elemnts are zeros.

# Example :
a=np.zeros((2,3))
print("Zeros:")
a

Zeros:
Ones:


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Ones ==> Ones is a numpy in-built function which is used to create a new array of with all elemnts are ones.

# Example :

b=np.ones((2,3))
print("Ones:")
b

Ones:


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# eye => eye is a numpy in-built function which is used to create a two-D array with ones on the diagonal /and resl all are zeros.

# example :

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# diag==> diag is a numpy in-built function which is used to create a two-D array with custom diagonal elements

# Example :

a=np.diag([1,2,3,4])
a


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# linspace=> linspace is a numpy in-built function which is used to create equal space between numbers withing given range .

# example :

np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# unique=> unique is a numpy in-built function which is used to find unique elements of an array.

# example:


array([1, 2, 3, 4, 5, 6])

In [ ]:
# Q4. What is hstack and vstack , explain with code of example?


# hstack => hstack is a numpy in-built function which is used to add arrays horizontally but it should have same number of rows.
# example:

a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
# vstack=> vstack is a numpy in-built function which is used to add arrays vertically but it should have same number of columns.
# example

np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Q5.What is view vs copy shoe me with the example

# view=> a view share memory with an array it means any change in view will reflect in original array.

# example :

a=np.array([1,2,3])
b=a.view()
b[0]=10
a

array([10,  2,  3])

In [ ]:
# copry=>  Copy means create a copry of original array ,
#         a copy does not share memory with an array it means any change in copy will not reflect in original array.

# example :

a=np.array([1,2,3])
b=a.copy()
b[0]=10
a

array([1, 2, 3])

In [ ]:
# Q6.you have to create two matix of shape (2,2) and perform matrix multiplication.

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.dot(a,b)   # dot is use for multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
# Q7. You have too create an array in range of 1 to 10 and then your have to reshape it (3,3) and then perform total sum , rowise sum , column wise sum

a=np.arange(1,10).reshape(3,3)
print(a)

# total sum :
print("Total : ",np.sum(a))

# Row wise sum :
print("Row wise : ", np.sum(a,axis=1))

# Column wise sum :
print("Column wise : ",np.sum(a,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Total :  45
Row wise :  [ 6 15 24]
Column wise :  [12 15 18]


In [ ]:

# Q8. What is random integer , rand , seed in Numpy Explain with the example of code

# randint=> randint is a numpy in-built function which is used to generate random integer between given range

# example:

print("Random integer : ", np.random.randint(1,10,5))


# rand=> rand is a numpy in-built function which is used to generate random numbers between 0 to 1

print("Rand : ",np.random.rand(5))


# seed=> seed is a numpy in-built function which is used to generate same random numbers every time it means it fix the value that given ones6.

np.random.seed(10)
print("seed: ",np.random.rand(5))

Random integer :  [1 2 9 1 9]
Rand :  [0.15037787 0.68381843 0.81660184 0.33607158 0.89081653]
seed:  [0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
