<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Advance_Python/NumPy_Question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Q.1 write statement to import numpy
import numpy as np

In [ ]:
#  Q.2 write statement to create array
a=[10,20,30,40]
b=np.array(a)
print(b)
print(type(b))

[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
# Q.3 create an array of 10 random intergers
a=np.random.randint(1,100,10)
print(a)
print(type(a))

[86 72 70 10 56 73 86 71  5 70]
<class 'numpy.ndarray'>


In [ ]:
# Q.4 create an array of elememt from 10-20?
a=np.arange(10,20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Q.5 create an array which contain values 5,10 times
a=np.ones(10)
print(a*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
# Q.6 create one dimension array and convert that into 3*3 matrix
a=np.random.randint(1,100,9).reshape((3,3))
print(a)

[[ 6 24  7]
 [34 98  7]
 [61 53 31]]


In [ ]:
#Q.7 create a 2d array of 3*3 but all the element should be between 0 to 1
a=np.random.rand(9).reshape((3,3))
print(a)

[[0.94306825 0.82574297 0.22853015]
 [0.17947081 0.15573745 0.32777365]
 [0.34388001 0.15489352 0.74755407]]


In [ ]:
# Q.8 concatenate 2D array horizontal and vertically
a=np.arange(1,10).reshape((3,3))
b=np.arange(21,30).reshape((3,3))
c=np.arange(31,40).reshape((3,3))
print(a)
print(b)
print(c)

print(np.vstack((a,b,c)))
print(np.hstack((a,b,c)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]
[[31 32 33]
 [34 35 36]
 [37 38 39]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [31 32 33]
 [34 35 36]
 [37 38 39]]
[[ 1  2  3 21 22 23 31 32 33]
 [ 4  5  6 24 25 26 34 35 36]
 [ 7  8  9 27 28 29 37 38 39]]
