<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Advance_Python/NumPy/NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NumPy : NumPy is a open-source library in python , use for scientific computing .
# its core object is ndarray.
# ndaary is faster then python sequences.00



In [ ]:
import numpy as np

In [ ]:
# create numpy array
# 1D Array

np.array([1,2,3])

# 2D Array
np.array([[1,2,3],[4,5,6]])

# 3D Array
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# dtype
a=np.array([1,2,3],dtype=float)

b=np.array([1,2,3],dtype='S')

c=np.array([1,2,3],dtype=complex)

print(a)
print(b)
print(c)
print(a.dtype)
print(b.dtype)
print(c.dtype)

[1. 2. 3.]
[b'1' b'2' b'3']
[1.+0.j 2.+0.j 3.+0.j]
float64
|S1
complex128


In [ ]:
# arange : arange() is a function used to create an array within a given range.

a=np.arange(0,10)
print(a)

b=np.arange(0,21,2)
print("Even numbers: ",b)

[0 1 2 3 4 5 6 7 8 9]
Even numbers:  [ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
# Reshape() : change the shape of array
# Reshaping condition
# n(rows) * n(columns) = n(total_elements)

# array size = row number * column number

a=np.arange(16).reshape(2,2,2,2)

b=np.arange(20).reshape(4,5)

print(a)

# print(b)


[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [ ]:
# NumPy array attributes

a1 = np.arange(10,dtype=int)

a2 = np.arange(12,dtype=float).reshape(3,4)

a3 = np.arange(8).reshape(2,2,2)

# ndim => tell the dimension of array

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
# Shape : define the shape of array

print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
# itemsize :tells you how many bytes each element of the array occupies in memory.
# returns the size (in bytes) of one element in the NumPy array.

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [ ]:
# size => tell size of array (total count of elements in array)

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
# astype :it  is a method used to convert the data type (dtype) of elements in a NumPy array.

a=np.arange(10,dtype=float)
print(a)
print("Before Convert :",a.dtype)
print("\n")

b=a.astype(int)
print(b)
print("After Convert :",b.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Before Convert : float64


[0 1 2 3 4 5 6 7 8 9]
After Convert : int64


**Numpy Pre-defined functions**



In [ ]:
# 1.zeros() ----> It will create an array in which all the values are 0 .
a = np.zeros(4)
print(a)

b=np.zeros(5,dtype=int)
print(b)


[0. 0. 0. 0.]
[0 0 0 0 0]


In [ ]:
# 2. ones() ---> It will create an array in which all the values are 1.

a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# (3). eye() ----> It will create an array in which digonal positional elements are 1 and rest all are 0.

a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# (4). diag() ----> It will set our custom values on digonal position .
a = np.array([1,45,78,90])
a

np.diag(a)

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [ ]:
# 5. random(): Random module is used to generate random numbers and random arrays from 0 to 1.
#              It is commonly used in simulations, machine learning, and testing.

np.random.random((3,4))

array([[0.34742146, 0.19757939, 0.31936432, 0.76933001],
       [0.68270984, 0.79681107, 0.46566246, 0.91393239],
       [0.30703429, 0.1800472 , 0.19034285, 0.86850947]])