<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Advance_Python/NumPy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NumPy : NumPy(Numerical Python) is a Python library used for fast numerical and scientific computing.

# It provides:
# Powerful N-dimensional array object (ndarray)
# Mathematical functions
# Linear algebra tools
# Random number generation
# Broadcasting operations

# It is the core library for numerical computation in Python and is used by libraries
#  like Pandas, SciPy, Scikit-learn, TensorFlow, and PyTorch.

# Interview definition:

# NumPy is a Python library that provides support for large multi-dimensional arrays and
#  matrices along with a collection of mathematical functions to operate on them efficiently.

In [ ]:
# ndarray : The ndarray (N-dimensional array) is the main data structure in NumPy.

# It is:
# A homogeneous array (all elements have same datatype)
# Stored in contiguous memory
# Much faster than Python lists

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])

arr
# arr.shape       #size of each dimension
# arr.ndim        #number of dimensions
# arr.dtype       #data type of elements

array([1, 2, 3, 4])

In [ ]:
# Why NumPy is Faster than Python Lists?

# NumPy is faster because:

# 1. Contiguous Memory Allocation

    # Elements are stored in continuous memory blocks, which improves performance.

# 2. Vectorized Operations

    # Operations are applied to entire arrays instead of loops.

# Example:

# Python list:

a=[1,2,3,4]
b=[1,2,3,4]
result = []
for i in range(len(a)):
    result.append(a[i] + b[i])
print(result)


# NumPy
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
result = a + b
print(result)


# 3. Implemented in C

    # NumPy core is written in C language, making operations extremely fast.

[2, 4, 6, 8]
[2 4 6 8]


In [ ]:
# | Feature                 | Python List               | NumPy Array          |
# | ----------------------- | ------------------------- | -------------------- |
# | Data Type               | Can store different types | Same type only       |
# | Speed                   | Slower                    | Much faster          |
# | Memory                  | More memory               | Less memory          |
# | Mathematical operations | Need loops                | Vectorized           |
# | Use case                | General purpose           | Scientific computing |


In [ ]:
# 5.Vectorization : Vectorization means performing operations on entire arrays without using loops.

# Example:
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b

# Output:

# [5 7 9]

# This is much faster than looping.

# Interview definition:

# Vectorization is the process of performing operations on whole arrays instead of element-by-element loops.

array([5, 7, 9])

In [ ]:
# 6. What is Broadcasting?

# Broadcasting allows arrays of different shapes to work together in arithmetic operations.

# Example:

a = np.array([1,2,3])
b = 2

a + b

# Output:
# [3 4 5]
# Here NumPy automatically expands the scalar value to match the array.

# Broadcasting rules:

# Dimensions must be equal or
# One of them must be 1

# Example:

# (3,4)
# (1,4)

# These shapes can broadcast.

array([3, 4, 5])

In [ ]:
# 7. What is Axis in NumPy?

# The axis defines the direction of operation in arrays.

# Example:

# array shape = (rows, columns)
# Axis	Meaning
# axis=0	column wise operation
# axis=1	row wise operation

# Example:

# np.sum(arr, axis=0)

# Sum of columns.

# np.sum(arr, axis=1)

# Sum of rows.

In [ ]:
# 8. Views vs Copies in NumPy:  Very important interview concept.

# View
# A view shares the same memory as the original array.

# a = np.array([1,2,3])
# b = a.view()

# Changing b will also change a.


# Copy
# A copy creates a completely new array.
# b = a.copy()

# Changes in b do not affect a.

In [ ]:
# 9. What is Shape and Reshape?

# Shape
# Shows the dimensions of the array.
# Example:

# (3,4)
# means 3 rows, 4 columns
# arr.shape




# Reshape
# Changes the structure of the array without changing data.

# Example:

a = np.arange(6)
a.reshape(3,2)

# Output:

# [[0 1 2]
#  [3 4 5]]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
# 10. What is Flattening?

# Flattening converts a multi-dimensional array into a 1D array.

# Example:

# arr.flatten()

# or

# arr.ravel()


# flatten()	==>   returns copy
# ravel()	  ==>   returns view

In [ ]:
# 11. What is NumPy Random Module?

# NumPy provides functions to generate random numbers for simulations and machine learning.

# Examples:

# np.random.rand()
# np.random.randn()
# np.random.randint()
# np.random.seed()

# Used in:

# ML model initialization
# Data simulation
# Testing algorithms

In [ ]:
# 12. Universal Functions (ufunc)

# Ufuncs are functions that operate element-wise on arrays.

# Examples:

# np.sqrt()
# np.exp()
# np.log()
# np.sin()
# np.add()

# Example:

np.sqrt([1,4,9])

# Output:

# [1 2 3]

array([1., 2., 3.])

In [ ]:
# 13. Memory Efficiency of NumPy

# NumPy uses less memory than Python lists because:

# It stores elements in fixed datatype

# Uses contiguous memory

# Avoids object overhead

In [ ]:
# 14. Why NumPy is Important for Data Science

# NumPy is the foundation of the Python data science ecosystem.

# Used in:
# Data manipulation

# Machine learning
# Linear algebra
# Statistics
# Image processing
# Deep learning


# Libraries built on NumPy:

# Pandas
# SciPy
# Scikit-learn
# TensorFlow
# PyTorch