<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Advance_Python/NumPy_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# introduction to numpy --->
#   NumPy ----> Num(Numerical) + Py(python)

#  this is an open - source library of python and this is used for scientfic calculations.

# list is hetrogenous(can mix datatype) data type and numpy is homogenous(same datatype) data type.



In [3]:
import numpy as np

In [1]:
a=[1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
a =np.array([1,2,3])
a*3

array([3, 6, 9])

In [5]:
a=[1,2,3]
b=np.array(a)
b

array([1, 2, 3])

In [7]:
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
a=[1,2,3],[4,5,6],[7,8,9]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print("Total shape: ", b.shape)
print("Total dimension: ", b.ndim)
print("Total size/elements: ", b.size)

Total shape:  (3, 3)
Total dimension:  2
Total size/elements:  9


In [ ]:
# pre-define functions of NumPy

In [13]:
# (1). Zeros ===> it will create an array in which all the values will be 0 in either
# one dimensional or multi-dimensional
a= np.zeros(3)
a

array([0., 0., 0.])

In [15]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# (2). Ones() ----> It will return an array in which all the values are 1 in either
# one dimension or multi-dimension

In [18]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [19]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])